const pg = require('pg')
const postgresURL  = process.env.DATABASE_URL || 'postgres://localhost/dealers_choice'
const client = new pg.Client(postgresURL)

const syncAndSeed = async() => {
    const SQL = `
    DROP TABLE IF EXISTS movies;
    CREATE TABLE movies(
        id SERIAL PRIMARY KEY,
        thumbnail VARCHAR(20),
        rating INTEGER,
        year INTEGER,
        title VARCHAR(100),
        director VARCHAR(100),
        summary VARCHAR(3000));


    INSERT INTO movies(thumbnail,rating,year,title,director,summary) VALUES('Shawshank.jpg',9.3,1994,'The Shawshank Redemption','Frank Darabont','After the murder of his wife, hotshot banker Andrew Dufresne is sent to Shawshank Prison, where the usual unpleasantness occurs. Over the years, he retains hope and eventually gains the respect of his fellow inmates, especially longtime convict "Red" Redding, a black marketeer, and becomes influential within the prison. Eventually, Andrew achieves his ends on his own terms.');
    INSERT INTO movies(thumbnail,rating,year,title,director,summary) VALUES('Godfather.jpg',9.2,1972,'The Godfather','Francis Ford Coppola','The Godfather "Don" Vito Corleone is the head of the Corleone mafia family in New York. He is at the event of his daughter''s wedding. Michael, Vito''s youngest son and a decorated WW II Marine is also present at the wedding. Michael seems to be uninterested in being a part of the family business. Vito is a powerful man, and is kind to all those who give him respect but is ruthless against those who do not. But when a powerful and treacherous rival wants to sell drugs and needs the Don''s influence for the same, Vito refuses to do it. What follows is a clash between Vito''s fading old values and the new ways which may cause Michael to do the thing he was most reluctant in doing and wage a mob war against all the other mafia families which could tear the Corleone family apart.');
    INSERT INTO movies(thumbnail,rating,year,title,director,summary) VALUES('TheDarkKnight.jpg',9,1974,'The Dark Knight','Christopher Nolan','Set within a year after the events of Batman Begins (2005), Batman, Lieutenant James Gordon, and new District Attorney Harvey Dent successfully begin to round up the criminals that plague Gotham City, until a mysterious and sadistic criminal mastermind known only as "The Joker" appears in Gotham, creating a new wave of chaos. Batman''s struggle against The Joker becomes deeply personal, forcing him to "confront everything he believes" and improve his technology to stop him. A love triangle develops between Bruce Wayne, Dent, and Rachel Dawes.');
    INSERT INTO movies(thumbnail,rating,year,title,director,summary) VALUES('Godfather_2.jpg',9,1974,'The Godfather: Part II','Francis Ford Coppola','The continuation of the Godfather saga with two focuses: the ongoing story of the Corleone family, and Michael in particular, and Vito Corleone''s (Michael''s father) backstory. Regarding the ongoing Michael Corleone story, it is about seven years since the events that concluded The Godfather. With the murders of the heads of the other four New York / New Jersey families, the Corleone family has unassailable control in New York. The move to Nevada went smoothly and Michael Corleone controls several hotels and casinos in the state. Frank Pentageli, the man who runs Michael''s interests in New York, comes to Michael, asking if he can take out the Rosato Brothers as they are infringing on Pentageli''s turf and business interests. However, the Rosatos are backed by Hyman Roth, a business partner of Michael''s and a long- time ally of Michael''s father, Vito Corleone, and Michael refuses. An attempted assassination attempt is then carried out on Michael''s life, in his own home. Michael investigates who is trying to kill him, and suspects that there is a traitor in his family. Meanwhile. Michael and Hyman Roth fly to Cuba to finalise some business deals there. The Cuban trip reveals all. In a story interwoven with the present day, we see the backstory to Vito Corleone. From how his parents and brother were murdered by a Don in their home town of Corleone in Sicily, to his escaping, as a boy, to New York, his adult life and his rise to Don Corleone.');
    INSERT INTO movies(thumbnail,rating,year,title,director,summary) VALUES('LOTR3.jpg',8.9,2003,'The Lord of the Rings: The Return of the King','Peter Jackson','Sauron''s forces have laid siege to Minas Tirith, the capital of Gondor, in their efforts to eliminate the race of men. The once-great kingdom, watched over by a fading Steward, has never been in more desperate need of its King. But can Aragorn answer the call of his heritage and become what he was born to be? In no small measure, the fate of Middle-earth rests on his broad shoulders. With the final battle joined, and the legions of darkness gathering, Gandalf urgently tries to rally Gondor''s broken army to action. He is aided by Rohan''s King Theoden, who unites his warriors for history''s biggest test. Yet even with their courage and passionate loyalty, the forces of men, with Eowyn and Merry hidden amongst them, are no match for the enemies swarming against Gondor. Still, in the face of great losses, they charge forward into the battle of their lifetimes, tied together by their singular goal to keep Sauron distracted and give the Ring Bearer a chance to complete his quest. Their hopes rest with Frodo, a tiny but determined Hobbit making a perilous trip across treacherous enemy lands to cast the One Ring into the fires of Mount Doom. The closer Frodo gets to his destination, the heavier his burden becomes, and the more he must rely on Samwise Gamgee. Gollum, and the Ring, will test Frodo''s allegiances and, ultimately, his humanity.');
    INSERT INTO movies(thumbnail,rating,year,title,director,summary) VALUES('PulpFiction.jpg',8.9,1994,'Pulp Fiction','Quentin Tarantino','Faced with life''s cruel irony, the unpredictable stories of a well-dressed pair of low-level hitmen; a gangster''s statuesque moll, and a double-crossing prizefighter become inextricably intertwined, as the small-time crooks, Honey Bunny and Pumpkin, summon up the courage to hold up their favourite L.A. diner. Entrusted with retrieving a glow-emitting leather suitcase which belongs to their boss--the powerful crime kingpin, Marsellus--instead, the dark-suited gunmen, Vincent Vega and Jules Winnfield, end up with a bloody mess. Fortunately--with men like Mr Wolf always around to handle a crisis--there''s time to cool off in a long twist contest, while at the same time, the proud champion boxer, Butch, makes the decision of a lifetime. Soon, things will come full circle, as, once more, Jules and Vincent find themselves in the perfect dead-end situation, exactly where it all began: an all-too-familiar cafeteria. Is truth stranger than fiction?');
    INSERT INTO movies(thumbnail,rating,year,title,director,summary) VALUES('SchindlersList.jpg',8.9,1993,'Schindler''s List','Steven Spielberg','Businessman Oskar Schindler arrives in Krakow in 1939, ready to make his fortune from World War II, which has just started. After joining the Nazi party primarily for political expediency, he staffs his factory with Jewish workers for similarly pragmatic reasons. When the SS begins exterminating Jews in the Krakow ghetto, Schindler arranges to have his workers protected to keep his factory in operation, but soon realizes that in so doing, he is also saving innocent lives.');
    INSERT INTO movies(thumbnail,rating,year,title,director,summary) VALUES('TwelveAngryMen.jpg',8.9,1957,'12 Angry Men','Sidney Lumet','"12 Angry Men" focuses on a jury''s deliberations in a capital murder case. A 12-man jury is sent to begin deliberations in the first-degree murder trial of an 18-year old Puerto Rican boy accused in the stabbing death of his father, where a guilty verdict means an automatic death sentence. The case appears to be open-and-shut: The defendant has a weak alibi; a knife he claimed to have lost is found at the murder scene; and several witnesses either heard screaming, saw the killing or the boy fleeing the scene. Eleven of the jurors immediately vote guilty; only Juror No. 8 (Mr. Davis) casts a not guilty vote. At first Mr. Davis bases his vote more so for the sake of discussion; after all, the jurors must believe beyond a reasonable doubt that the defendant is guilty. As the deliberations unfold, the story quickly becomes a study of the jurors'' complex personalities (which range from wise, bright and empathetic to arrogant, prejudiced and merciless), preconceptions, backgrounds and interactions. That provides the backdrop to Mr. Davis'' attempts in convincing the other jurors that a "not guilty" verdict might be appropriate.');
    INSERT INTO movies(thumbnail,rating,year,title,director,summary) VALUES('Inception.jpg',8.8,2010,'Inception','Christopher Nolan','Dom Cobb is a skilled thief, the absolute best in the dangerous art of extraction, stealing valuable secrets from deep within the subconscious during the dream state, when the mind is at its most vulnerable. Cobb''s rare ability has made him a coveted player in this treacherous new world of corporate espionage, but it has also made him an international fugitive and cost him everything he has ever loved. Now Cobb is being offered a chance at redemption. One last job could give him his life back but only if he can accomplish the impossible, inception. Instead of the perfect heist, Cobb and his team of specialists have to pull off the reverse: their task is not to steal an idea, but to plant one. If they succeed, it could be the perfect crime. But no amount of careful planning or expertise can prepare the team for the dangerous enemy that seems to predict their every move. An enemy that only Cobb could have seen coming');
    INSERT INTO movies(thumbnail,rating,year,title,director,summary) VALUES('FightClub.jpg',8.8,1999,'Fight Club','David Fincher','A nameless first person narrator (Edward Norton) attends support groups in attempt to subdue his emotional state and relieve his insomniac state. When he meets Marla (Helena Bonham Carter), another fake attendee of support groups, his life seems to become a little more bearable. However when he associates himself with Tyler (Brad Pitt) he is dragged into an underground fight club and soap making scheme. Together the two men spiral out of control and engage in competitive rivalry for love and power. When the narrator is exposed to the hidden agenda of Tyler''s fight club, he must accept the awful truth that Tyler may not be who he says he is.');
    `
    await client.query(SQL)
}

module.exports = {
    client,
    syncAndSeed
}